name: Tests

on: [push]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu:21.04

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: database_ci
          MYSQL_USER: user
          MYSQL_PASSWORD: secret
          MYSQL_ROOT_PASSWORD: secretroot
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v1

      - name: Verify MySQL connection
        run: |
          mysql --version
          sudo apt-get update
          sudo apt-get install -y mysql-client
          mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uuser -psecret -e "SHOW DATABASES"
      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - name: Install dependencies
        run: |
          php --version
          composer install -n --prefer-dist
      - name: Boot Laravel application
        run: |
          cp .env.github .env
          key=$(php artisan key:generate --show)
          echo "APP_KEY=$key" >> .env
          echo "Running with environment variables: "
          cat .env
          ./artisan --version
          ./artisan config:cache
      - name: Migrate database
        run: |
          mysql --version
          php artisan migrate:fresh --seed
      - name: Cache yarn dependencies
        uses: actions/cache@v1
        with:
          path: node_modules
          key: yarn-${{ hashFiles('yarn.lock') }}
      - name: Run yarn
        run: |
          yarn --version
          yarn && yarn dev
      - name: Run tests
        run: |
          ./artisan serve &
          ./vendor/bin/phpunit --version
          ./vendor/bin/phpunit
      - name: Run dusk tests
        run: |
          ./artisan dusk:chrome-driver 84
          nohup bash -c './vendor/laravel/dusk/bin/chromedriver-linux > /dev/null 2>&1 &'
          ./artisan dusk          
      - name: Run security checks
        run: |
          test -d security-checker || git clone https://github.com/sensiolabs/security-checker.git
          cd security-checker
          composer install
          php security-checker security:check ./composer.lock
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: Logs
          path: /storage/logs
